import 'dart:html' as html;
import 'dart:typed_data';

import 'package:business_manager_web_ui/l10n/app_localizations.dart';
import 'package:business_manager_web_ui/src/app/animations/loading_animation.dart';
import 'package:business_manager_web_ui/src/app/constants/error_class.dart';
import 'package:business_manager_web_ui/src/app/utils/components/snackbar_widget.dart';
import 'package:business_manager_web_ui/src/app/utils/pdf_generators/statement_pdf.dart';
import 'package:business_manager_web_ui/src/app/widgets/Text/my_text.dart';
import 'package:business_manager_web_ui/src/app/widgets/buttons/skeleton_loading.dart';
import 'package:business_manager_web_ui/src/models/client_model.dart';
import 'package:business_manager_web_ui/src/models/client_statement.dart';
import 'package:business_manager_web_ui/src/models/user_model.dart';
import 'package:business_manager_web_ui/src/services/client_service.dart';
import 'package:business_manager_web_ui/src/services/database_service.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import '../../app/theme/responsive_utils.dart';
import '../../services/auth_service.dart';

/// Stage 15 scope: client statement — a running-balance ledger table with a
/// PDF export. Turned out to be fully portable (PDF *generation* is pure
/// Dart via `syncfusion_flutter_pdf`, the same package family as the Home
/// dashboard's chart widget which already proved out on web in Stage 11) —
/// only the "save + open" mechanism at the end needed a web-native
/// replacement. Mobile writes the generated bytes to a temp file
/// (`path_provider`) and hands it to the OS's default PDF viewer
/// (`open_app_file`); the web equivalent is triggering a direct browser
/// download of the same in-memory bytes via `dart:html`.
class ClientStatment extends StatefulWidget {
  const ClientStatment({super.key, this.uid, this.clientId});
  final String? uid;
  final String? clientId;

  @override
  State<ClientStatment> createState() => _ClientStatmentState();
}

class _ClientStatmentState extends State<ClientStatment> {
  //Initials
  ResponsiveUtils? responsive;
  AppLocalizations? appLoc;
  //Service
  ErrorClass errorClass = ErrorClass();
  AuthService as = AuthService();
  ClientService cs = ClientService();
  SnackbarWidget snackbarWidget = SnackbarWidget();
  DatabaseService db = DatabaseService();
  //Variables
  bool isLoading = false,
      isSearching = false,
      isIndividual = true,
      isUpdating = false;
  //get user
  late Future<List<dynamic>> _statementFutures;
  var numberFormat = NumberFormat('#,##0.00', 'en_US');

  @override
  void didChangeDependencies() {
    appLoc = AppLocalizations.of(context);
    responsive = ResponsiveUtils(context);
    snackbarWidget.context = context;
    super.didChangeDependencies();
  }

  @override
  void initState() {
    _statementFutures = Future.wait([
      db.getCurrentUser(uid: widget.uid),
      cs.futureSingleClient(widget.uid, widget.clientId),
    ]);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: SafeArea(
        child: FutureBuilder<List<dynamic>>(
            future: _statementFutures,
            builder: (context, futureSnapshot) {
              if (futureSnapshot.connectionState == ConnectionState.waiting) {
                return const GradientSkeleton();
              }
              if (futureSnapshot.hasError) {
                return Center(
                    child: MyText(text: errorClass.userNoTFoundError()));
              }

              final currentUser = futureSnapshot.data![0] as UserDetails;
              final client = futureSnapshot.data![1] as ClientDetails;
              return StreamBuilder<List<StatementRecord>>(
                  stream: cs.streamClientRecords(
                      uid: widget.uid, clientId: widget.clientId),
                  builder: (context, statementshot) {
                    if (statementshot.hasError) {
                      return Center(
                        child: MyText(
                          text: errorClass.userNoTFoundError(),
                        ),
                      );
                    } else if (statementshot.connectionState ==
                        ConnectionState.waiting) {
                      return const GradientSkeleton();
                    } else {
                      return Scaffold(
                        appBar: AppBar(
                          title: MyText(
                            text: appLoc!.clientStatement,
                            fontScale: responsive!.scaleFont(25),
                          ),
                          actions: [
                            //will generate a pdf form for the statement
                            GestureDetector(
                              onTap: () async {
                                setState(() {
                                  isLoading = true;
                                });

                                await downloadStatementPdf(currentUser, client,
                                    statementshot.data ?? []);

                                if (mounted) {
                                  setState(() {
                                    isLoading = false;
                                  });
                                }
                              },
                              child: Padding(
                                padding: responsive!.responsivePaddingRight,
                                child: Icon(
                                  Icons.picture_as_pdf_rounded,
                                  size: responsive!.scaleHeight(30),
                                ),
                              ),
                            )
                          ],
                          backgroundColor:
                              Theme.of(context).scaffoldBackgroundColor,
                        ),
                        body: Stack(
                          children: [
                            _buildClientStatementBody(statementshot.data ?? []),
                            isLoading
                                ? const Center(child: AnimatedArcLoader())
                                : const SizedBox.shrink()
                          ],
                        ),
                      );
                    }
                  });
            }),
      ),
    );
  }

  Widget _buildClientStatementBody(List<StatementRecord> records) {
    // Calculate running total and summary values
    double runningTotal = 0;
    double totalDebit = 0;
    double totalCredit = 0;
    final List<Map<String, dynamic>> rows = records.map((record) {
      final value = record.value ?? 0.0;
      if (record.type == 'debit') {
        runningTotal -= value;
        totalDebit += value;
      } else {
        runningTotal += value;
        totalCredit += value;
      }
      return {
        'record': record,
        'runningTotal': runningTotal,
      };
    }).toList();
    return Column(
      children: [
        // ── Header Row ──────────────────────────────────────────────
        Container(
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 8),
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.1),
            border: Border(
              bottom: BorderSide(
                color: Theme.of(context).dividerColor,
                width: 1.5,
              ),
            ),
          ),
          child: Row(
            children: [
              _headerCell('Date', flex: 2),
              _headerCell('Record ID', flex: 2),
              _headerCell('Debit', flex: 2, align: TextAlign.right),
              _headerCell('Credit', flex: 2, align: TextAlign.right),
              _headerCell('Total', flex: 2, align: TextAlign.right),
            ],
          ),
        ),
        // ── Records ─────────────────────────────────────────────────
        Expanded(
          child: ListView.builder(
            itemCount: rows.length,
            itemBuilder: (context, index) {
              final record = rows[index]['record'] as StatementRecord;
              final double runTotal = rows[index]['runningTotal'] as double;
              final bool isDebit = record.type == 'debit';
              final value = record.value ?? 0.0;
              final date = record.entryDate;

              return Container(
                padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 8),
                decoration: BoxDecoration(
                  color: index.isEven
                      ? Colors.transparent
                      : Theme.of(context)
                          .colorScheme
                          .surface
                          .withValues(alpha: 0.4),
                  border: Border(
                    bottom: BorderSide(
                      color:
                          Theme.of(context).dividerColor.withValues(alpha: 0.4),
                    ),
                  ),
                ),
                child: Row(
                  children: [
                    // Date
                    Expanded(
                      flex: 2,
                      child: MyText(
                        text: date != null
                            ? '${date.day.toString().padLeft(2, '0')}/'
                                '${date.month.toString().padLeft(2, '0')}/'
                                '${date.year}'
                            : '-',
                        fontScale: responsive!.scaleFont(10),
                      ),
                    ),
                    // Record ID
                    Expanded(
                      flex: 2,
                      child: MyText(
                        text: record.uid ?? '-',
                        fontScale: responsive!.scaleFont(10),
                      ),
                    ),
                    // Debit (left side)
                    Expanded(
                      flex: 2,
                      child: isDebit
                          ? MyText(
                              text: numberFormat.format(value),
                              fontColor: Colors.red,
                              align: TextAlign.right,
                              fontScale: responsive!.scaleFont(10),
                              maxLines: 1,
                              textOverflow: TextOverflow.ellipsis,
                              softWrap: false,
                            )
                          : const SizedBox.shrink(),
                    ),
                    // Credit (right side)
                    Expanded(
                      flex: 2,
                      child: !isDebit
                          ? MyText(
                              text: numberFormat.format(value),
                              fontColor: Colors.green,
                              align: TextAlign.right,
                              fontScale: responsive!.scaleFont(10),
                              maxLines: 1,
                              textOverflow: TextOverflow.ellipsis,
                              softWrap: false,
                            )
                          : const SizedBox.shrink(),
                    ),
                    // Running Total
                    Expanded(
                      flex: 2,
                      child: MyText(
                        text: numberFormat.format(runTotal),
                        fontColor: runTotal >= 0 ? Colors.green : Colors.red,
                        align: TextAlign.right,
                        fontWeight: FontWeight.bold,
                        fontScale: responsive!.scaleFont(10),
                        maxLines: 1,
                        textOverflow: TextOverflow.ellipsis,
                        softWrap: false,
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ),

        // ── Footer / Totals Row ──────────────────────────────────────
        Container(
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 8),
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.primary.withValues(alpha: 0.1),
            border: Border(
              top: BorderSide(
                color: Theme.of(context).dividerColor,
                width: 1.5,
              ),
            ),
          ),
          child: Row(
            children: [
              // Date column — blank
              const Expanded(flex: 2, child: SizedBox.shrink()),
              // Total count
              Expanded(
                flex: 2,
                child: MyText(
                  text: '${records.length} records',
                  fontWeight: FontWeight.bold,
                ),
              ),
              // Total Debit
              Expanded(
                flex: 2,
                child: MyText(
                  text: numberFormat.format(totalDebit),
                  fontColor: Colors.red,
                  fontWeight: FontWeight.bold,
                  align: TextAlign.right,
                  fontScale: responsive!.scaleFont(10),
                  maxLines: 1,
                  textOverflow: TextOverflow.ellipsis,
                  softWrap: false,
                ),
              ),
              // Total Credit
              Expanded(
                flex: 2,
                child: MyText(
                  text: numberFormat.format(totalCredit),
                  fontColor: Colors.green,
                  fontWeight: FontWeight.bold,
                  align: TextAlign.right,
                  fontScale: responsive!.scaleFont(10),
                  maxLines: 1,
                  textOverflow: TextOverflow.ellipsis,
                  softWrap: false,
                ),
              ),
              // Net Total
              Expanded(
                flex: 2,
                child: MyText(
                  text: numberFormat.format(runningTotal),
                  fontColor: runningTotal >= 0 ? Colors.green : Colors.red,
                  fontWeight: FontWeight.bold,
                  align: TextAlign.right,
                  fontScale: responsive!.scaleFont(10),
                  maxLines: 1,
                  textOverflow: TextOverflow.ellipsis,
                  softWrap: false,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  // Helper for header cells
  Widget _headerCell(String label,
      {int flex = 1, TextAlign align = TextAlign.left}) {
    return Expanded(
      flex: flex,
      child: MyText(
        text: label,
        fontWeight: FontWeight.bold,
        align: align,
      ),
    );
  }

  // Generates the PDF, then triggers a direct browser download of the bytes
  // — the web equivalent of mobile's write-to-temp-file + open-in-native-app.
  Future<void> downloadStatementPdf(UserDetails currentUser,
      ClientDetails client, List<StatementRecord> data) async {
    try {
      final PdfDocument doc = await generateClientStatement(
          currentUser: currentUser,
          client: client,
          records: data,
          appLoc: appLoc!);

      final List<int> bytes = await doc.save();
      doc.dispose();

      // html.Blob needs a typed-data view (Uint8List), not a raw List<int> —
      // passing the List directly serializes it as its string representation
      // ("37,80,68,70,...") instead of the actual binary bytes, silently
      // producing a corrupt "PDF".
      final blob = html.Blob([Uint8List.fromList(bytes)], 'application/pdf');
      final url = html.Url.createObjectUrlFromBlob(blob);
      html.AnchorElement(href: url)
        ..setAttribute('download', 'statement_${widget.clientId}.pdf')
        ..click();
      html.Url.revokeObjectUrl(url);
    } on Exception catch (e) {
      snackbarWidget.content = '${appLoc!.error}: $e';
      snackbarWidget.showSnack();
    }
  }
}
